{pkgs, ...}: {
  # --- Locale ---------------------------------------------------------------
  # Keep en_US.UTF-8 as the system/UI language (the existing default),
  # but also generate the Chinese locale so that LC_* categories, date/time
  # formatting and translated messages are available when needed.
  # (`i18n.supportedLocales` is deprecated on current nixpkgs — use
  #  `i18n.extraLocales`; en_US.UTF-8 and C.UTF-8 are generated by default.)
  i18n.extraLocales = [
    "zh_CN.UTF-8/UTF-8"
  ];

  # --- Input method (IME) ---------------------------------------------------
  # fcitx5 is the standard CJK input framework and speaks the Wayland
  # `text-input-v3` protocol that niri implements.
  #
  # `waylandFrontend = true` is the modern, recommended Wayland setup: it
  # sets only `XMODIFIERS=@im=fcitx` (for XWayland apps) and leaves
  # `GTK_IM_MODULE` / `QT_IM_MODULE` *unset*, so native GTK4/Qt6 apps talk
  # to fcitx5 through the Wayland text-input protocol instead of the legacy
  # IM modules (which misbehave on modern Wayland).
  i18n.inputMethod = {
    enable = true;
    type = "fcitx5";

    fcitx5.waylandFrontend = true;

    fcitx5.addons = with pkgs; [
      qt6Packages.fcitx5-chinese-addons # Pinyin + table input (拼音/双拼/笔画/…)
      fcitx5-rime # RIME 中州韵 — powerful, highly customizable engine
      fcitx5-gtk # GTK immodule (XWayland / legacy GTK apps)
      qt6Packages.fcitx5-qt # Qt6 immodule (XWayland / legacy Qt apps)
      kdePackages.fcitx5-configtool # GUI configuration utility
    ];

    # Default input-method profile so Chinese input works out of the box,
    # without having to open the config tool first. Changes made through
    # the GUI (written to ~/.config/fcitx5/profile) take precedence.
    fcitx5.settings.inputMethod = {
      GroupOrder."0" = "Default";
      "Groups/0" = {
        Name = "Default";
        "Default Layout" = "us";
        DefaultIM = "pinyin";
      };
      "Groups/0/Items/0".Name = "keyboard-us";
      "Groups/0/Items/1".Name = "pinyin";
    };
  };
}
